/**
 * Offscreen Document - For heavy compute (WebGPU) and background tasks
 * Placeholder for MVP - will handle:
 * - Local LLM inference via WebGPU
 * - Audio processing for voice features
 * - Heavy computation offloading
 */

// Offscreen config for Plasmo
export const config = {
  reasons: ["WEB_RTC", "WORKERS"] as const,
  justification: "WebGPU/WebRTC for local AI inference and voice features",
}


interface OffscreenTask {
  id: string
  type: "inference" | "audio" | "compute"
  input: unknown
}

interface OffscreenResult {
  id: string
  success: boolean
  output?: unknown
  error?: string
}

// Task queue
const taskQueue: OffscreenTask[] = []
let isProcessing = false

// Listen for tasks from Service Worker
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === "OFFSCREEN_TASK") {
    const task = message.payload as OffscreenTask
    queueTask(task)
      .then((result) => sendResponse(result))
      .catch((error) => sendResponse({ id: task.id, success: false, error: String(error) }))
    return true
  }
})

async function queueTask(task: OffscreenTask): Promise<OffscreenResult> {
  taskQueue.push(task)
  
  if (!isProcessing) {
    isProcessing = true
    return processQueue(task.id)
  }
  
  // Wait for task to be processed
  return new Promise((resolve) => {
    const interval = setInterval(() => {
      const result = completedResults.get(task.id)
      if (result) {
        clearInterval(interval)
        completedResults.delete(task.id)
        resolve(result)
      }
    }, 100)
  })
}

const completedResults = new Map<string, OffscreenResult>()

async function processQueue(waitForId?: string): Promise<OffscreenResult> {
  let result: OffscreenResult | undefined
  
  while (taskQueue.length > 0) {
    const task = taskQueue.shift()!
    const taskResult = await processTask(task)
    completedResults.set(task.id, taskResult)
    
    if (task.id === waitForId) {
      result = taskResult
    }
  }
  
  isProcessing = false
  return result || { id: waitForId || "", success: false, error: "Task not found" }
}

async function processTask(task: OffscreenTask): Promise<OffscreenResult> {
  // MVP: Return mock results
  switch (task.type) {
    case "inference":
      // Placeholder for WebGPU LLM inference
      return {
        id: task.id,
        success: true,
        output: {
          text: "[Mock inference output] This would be generated by a local LLM via WebGPU",
          tokens: 42,
          latency_ms: 150,
        },
      }
    
    case "audio":
      // Placeholder for audio processing
      return {
        id: task.id,
        success: true,
        output: {
          transcript: "[Mock transcription] Voice input would be transcribed here",
          confidence: 0.95,
        },
      }
    
    case "compute":
      // Placeholder for heavy computation
      return {
        id: task.id,
        success: true,
        output: { computed: true, result: task.input },
      }
    
    default:
      return { id: task.id, success: false, error: `Unknown task type: ${task.type}` }
  }
}

console.log("[Collider] Offscreen document loaded")
