"""Streaming support for collider-sdk.

Handles Server-Sent Events (SSE) streaming with token-by-token
agent responses.
"""

import logging
from typing import Any, AsyncGenerator, Dict, Optional

import httpx

from sdk.models import AgentRunRequest

logger = logging.getLogger(__name__)


class StreamingResponse:
    """Represents a streaming agent response.

    Allows token-by-token consumption of agent response with
    automatic error handling.
    """

    def __init__(self, response: httpx.Response):
        """Initialize streaming response.

        Args:
            response: httpx.Response with streaming content
        """
        self.response = response
        self._buffer = ""

    async def iter_tokens(self) -> AsyncGenerator[str, None]:
        """Iterate over response tokens.

        Yields:
            Individual tokens/chunks from agent response

        Example:
            ```python
            async with client.run_agent_stream(message) as stream:
                async for token in stream.iter_tokens():
                    print(token, end="", flush=True)
            ```
        """
        try:
            async for line in self.response.aiter_lines():
                if not line or line.startswith(":"):
                    # Skip empty lines and comments
                    continue

                if line.startswith("data: "):
                    data = line[6:]
                    if data == "[DONE]":
                        break

                    try:
                        import json

                        event = json.loads(data)

                        if event.get("type") == "token":
                            token = event.get("token", "")
                            yield token
                        elif event.get("type") == "error":
                            raise RuntimeError(f"Stream error: {event.get('message')}")

                    except ValueError:
                        logger.warning(f"Failed to parse SSE event: {data}")
                        continue

        except httpx.StreamClosed:  # Fixed: StreamClosedError doesn't exist in httpx
            logger.warning("Stream closed unexpectedly")
        finally:
            await self.response.aclose()

    async def iter_text(self) -> AsyncGenerator[str, None]:
        """Iterate over complete text chunks.

        Buffers tokens and yields on punctuation boundaries.

        Yields:
            Text chunks (usually sentences or paragraphs)
        """
        punctuation = ".!?;\n"

        async for token in self.iter_tokens():
            self._buffer += token

            while any(self._buffer.endswith(p) for p in punctuation):
                # Find the first punctuation mark
                min_idx = len(self._buffer)
                for p in punctuation:
                    idx = self._buffer.rfind(p)
                    if idx >= 0:
                        min_idx = min(min_idx, idx + 1)

                if min_idx < len(self._buffer):
                    yield self._buffer[:min_idx]
                    self._buffer = self._buffer[min_idx:]
                else:
                    break

        # Yield remaining buffer
        if self._buffer:
            yield self._buffer

    async def get_full_response(self) -> str:
        """Get complete response as a single string.

        Returns:
            Full agent response

        Example:
            ```python
            async with client.run_agent_stream(message) as stream:
                full_response = await stream.get_full_response()
            ```
        """
        chunks = []
        async for chunk in self.iter_text():
            chunks.append(chunk)
        return "".join(chunks)

    async def __aenter__(self) -> "StreamingResponse":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.response.aclose()


class ColliderStreamingClient:
    """Mixin for streaming support in ColliderClient.

    Add to ColliderClient to enable streaming agent responses.
    """

    async def run_agent_stream(
        self,
        message: str,
        session_id: Optional[str] = None,
        model: Optional[str] = None,
    ) -> StreamingResponse:
        """Execute agent with streaming response.

        Streams tokens as they're generated by the model for
        real-time display in UIs.

        Args:
            message: User message
            session_id: Existing session ID or None to create new
            model: Override default model

        Returns:
            StreamingResponse for iteration

        Raises:
            httpx.HTTPStatusError: If API call fails
            TokenExpiredError: If token expired

        Example:
            ```python
            async with client.run_agent_stream(
                message="Analyze this data"
            ) as stream:
                async for token in stream.iter_tokens():
                    print(token, end="", flush=True)
            ```
        """
        req = AgentRunRequest(
            message=message,
            session_id=session_id,
            stream=True,
            model=model,
        )

        response = await self._client.stream(  # type: ignore[attr-defined]
            "POST",
            f"{self.api_url}/agent/stream",  # type: ignore[attr-defined]
            json=req.model_dump(exclude_none=True),
            headers=self._get_headers(),  # type: ignore[attr-defined]
        )

        response.raise_for_status()
        return StreamingResponse(response)

    async def run_agent_stream_to_file(
        self,
        message: str,
        filepath: str,
        session_id: Optional[str] = None,
        model: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Stream agent response directly to file.

        Args:
            message: User message
            filepath: Path to save response
            session_id: Existing session ID
            model: Override model

        Returns:
            Metadata dict with token count, timing, etc.

        Example:
            ```python
            metadata = await client.run_agent_stream_to_file(
                message="Generate report",
                filepath="report.txt"
            )
            print(f"Saved {metadata['tokens']} tokens to file")
            ```
        """
        token_count = 0
        import time

        start_time = time.time()

        with open(filepath, "w") as f:
            async with await self.run_agent_stream(message, session_id, model) as stream:
                async for chunk in stream.iter_text():
                    f.write(chunk)
                    token_count += len(chunk.split())

        elapsed = time.time() - start_time

        return {
            "filepath": filepath,
            "tokens": token_count,
            "duration_seconds": elapsed,
            "tokens_per_second": token_count / elapsed if elapsed > 0 else 0,
        }
