# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import collider_graph_pb2 as collider__graph__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collider_graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ColliderGraphStub(object):
    """---------------------------------------------------------------------------
    ColliderGraph — gRPC service on the GraphToolServer (:8001)

    Manages the living graph of tools and workflows.  Agents discover
    and execute tools/subgraphs through this service.
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTool = channel.unary_unary(
                '/collider.graph.ColliderGraph/RegisterTool',
                request_serializer=collider__graph__pb2.RegisterToolRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.RegisterWorkflow = channel.unary_unary(
                '/collider.graph.ColliderGraph/RegisterWorkflow',
                request_serializer=collider__graph__pb2.RegisterWorkflowRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.RegisterWorkflowResponse.FromString,
                _registered_method=True)
        self.DiscoverTools = channel.unary_unary(
                '/collider.graph.ColliderGraph/DiscoverTools',
                request_serializer=collider__graph__pb2.ToolDiscoveryRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.ToolDiscoveryResponse.FromString,
                _registered_method=True)
        self.ExecuteSubgraph = channel.unary_unary(
                '/collider.graph.ColliderGraph/ExecuteSubgraph',
                request_serializer=collider__graph__pb2.SubgraphRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.SubgraphResponse.FromString,
                _registered_method=True)
        self.ExecuteSubgraphStream = channel.unary_stream(
                '/collider.graph.ColliderGraph/ExecuteSubgraphStream',
                request_serializer=collider__graph__pb2.SubgraphRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.SubgraphProgress.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/collider.graph.ColliderGraph/ExecuteTool',
                request_serializer=collider__graph__pb2.ToolExecutionRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.ToolExecutionResponse.FromString,
                _registered_method=True)


class ColliderGraphServicer(object):
    """---------------------------------------------------------------------------
    ColliderGraph — gRPC service on the GraphToolServer (:8001)

    Manages the living graph of tools and workflows.  Agents discover
    and execute tools/subgraphs through this service.
    ---------------------------------------------------------------------------

    """

    def RegisterTool(self, request, context):
        """Register a tool as a Pydantic Graph step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorkflow(self, request, context):
        """Register a workflow as a subgraph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverTools(self, request, context):
        """Discover tools matching a query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSubgraph(self, request, context):
        """Execute a subgraph (workflow) and get the result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSubgraphStream(self, request, context):
        """Stream execution progress for a subgraph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Execute a single registered tool by name (no workflow wrapper required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColliderGraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=collider__graph__pb2.RegisterToolRequest.FromString,
                    response_serializer=collider__graph__pb2.RegisterToolResponse.SerializeToString,
            ),
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=collider__graph__pb2.RegisterWorkflowRequest.FromString,
                    response_serializer=collider__graph__pb2.RegisterWorkflowResponse.SerializeToString,
            ),
            'DiscoverTools': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverTools,
                    request_deserializer=collider__graph__pb2.ToolDiscoveryRequest.FromString,
                    response_serializer=collider__graph__pb2.ToolDiscoveryResponse.SerializeToString,
            ),
            'ExecuteSubgraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSubgraph,
                    request_deserializer=collider__graph__pb2.SubgraphRequest.FromString,
                    response_serializer=collider__graph__pb2.SubgraphResponse.SerializeToString,
            ),
            'ExecuteSubgraphStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteSubgraphStream,
                    request_deserializer=collider__graph__pb2.SubgraphRequest.FromString,
                    response_serializer=collider__graph__pb2.SubgraphProgress.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=collider__graph__pb2.ToolExecutionRequest.FromString,
                    response_serializer=collider__graph__pb2.ToolExecutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collider.graph.ColliderGraph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collider.graph.ColliderGraph', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColliderGraph(object):
    """---------------------------------------------------------------------------
    ColliderGraph — gRPC service on the GraphToolServer (:8001)

    Manages the living graph of tools and workflows.  Agents discover
    and execute tools/subgraphs through this service.
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderGraph/RegisterTool',
            collider__graph__pb2.RegisterToolRequest.SerializeToString,
            collider__graph__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderGraph/RegisterWorkflow',
            collider__graph__pb2.RegisterWorkflowRequest.SerializeToString,
            collider__graph__pb2.RegisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderGraph/DiscoverTools',
            collider__graph__pb2.ToolDiscoveryRequest.SerializeToString,
            collider__graph__pb2.ToolDiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSubgraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderGraph/ExecuteSubgraph',
            collider__graph__pb2.SubgraphRequest.SerializeToString,
            collider__graph__pb2.SubgraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSubgraphStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/collider.graph.ColliderGraph/ExecuteSubgraphStream',
            collider__graph__pb2.SubgraphRequest.SerializeToString,
            collider__graph__pb2.SubgraphProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderGraph/ExecuteTool',
            collider__graph__pb2.ToolExecutionRequest.SerializeToString,
            collider__graph__pb2.ToolExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ColliderContextStub(object):
    """===========================================================================
    ColliderContext — gRPC service for agent context delivery

    Replaces filesystem-based context injection (CLAUDE.md, SKILL.md, .mcp.json)
    with programmatic gRPC streaming from AgentRunner to NanoClawBridge.
    ===========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamContext = channel.unary_stream(
                '/collider.graph.ColliderContext/StreamContext',
                request_serializer=collider__graph__pb2.ContextRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.ContextChunk.FromString,
                _registered_method=True)
        self.SubscribeContextDeltas = channel.unary_stream(
                '/collider.graph.ColliderContext/SubscribeContextDeltas',
                request_serializer=collider__graph__pb2.DeltaSubscription.SerializeToString,
                response_deserializer=collider__graph__pb2.ContextDelta.FromString,
                _registered_method=True)
        self.GetBootstrap = channel.unary_unary(
                '/collider.graph.ColliderContext/GetBootstrap',
                request_serializer=collider__graph__pb2.ContextRequest.SerializeToString,
                response_deserializer=collider__graph__pb2.BootstrapResponse.FromString,
                _registered_method=True)


class ColliderContextServicer(object):
    """===========================================================================
    ColliderContext — gRPC service for agent context delivery

    Replaces filesystem-based context injection (CLAUDE.md, SKILL.md, .mcp.json)
    with programmatic gRPC streaming from AgentRunner to NanoClawBridge.
    ===========================================================================

    """

    def StreamContext(self, request, context):
        """Initial context delivery: stream full composed context as typed chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeContextDeltas(self, request, context):
        """Live delta subscription: receive NodeContainer mutations mid-session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBootstrap(self, request, context):
        """One-shot bootstrap: get full composed context as single response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColliderContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamContext': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamContext,
                    request_deserializer=collider__graph__pb2.ContextRequest.FromString,
                    response_serializer=collider__graph__pb2.ContextChunk.SerializeToString,
            ),
            'SubscribeContextDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeContextDeltas,
                    request_deserializer=collider__graph__pb2.DeltaSubscription.FromString,
                    response_serializer=collider__graph__pb2.ContextDelta.SerializeToString,
            ),
            'GetBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBootstrap,
                    request_deserializer=collider__graph__pb2.ContextRequest.FromString,
                    response_serializer=collider__graph__pb2.BootstrapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collider.graph.ColliderContext', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collider.graph.ColliderContext', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColliderContext(object):
    """===========================================================================
    ColliderContext — gRPC service for agent context delivery

    Replaces filesystem-based context injection (CLAUDE.md, SKILL.md, .mcp.json)
    with programmatic gRPC streaming from AgentRunner to NanoClawBridge.
    ===========================================================================

    """

    @staticmethod
    def StreamContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/collider.graph.ColliderContext/StreamContext',
            collider__graph__pb2.ContextRequest.SerializeToString,
            collider__graph__pb2.ContextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeContextDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/collider.graph.ColliderContext/SubscribeContextDeltas',
            collider__graph__pb2.DeltaSubscription.SerializeToString,
            collider__graph__pb2.ContextDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.graph.ColliderContext/GetBootstrap',
            collider__graph__pb2.ContextRequest.SerializeToString,
            collider__graph__pb2.BootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
