# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import collider_vectordb_pb2 as collider__vectordb__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collider_vectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ColliderVectorDbStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexTool = channel.unary_unary(
                '/collider_vectordb.ColliderVectorDb/IndexTool',
                request_serializer=collider__vectordb__pb2.ToolIndexRequest.SerializeToString,
                response_deserializer=collider__vectordb__pb2.ToolIndexResponse.FromString,
                _registered_method=True)
        self.SearchTools = channel.unary_unary(
                '/collider_vectordb.ColliderVectorDb/SearchTools',
                request_serializer=collider__vectordb__pb2.ToolSearchRequest.SerializeToString,
                response_deserializer=collider__vectordb__pb2.ToolSearchResponse.FromString,
                _registered_method=True)


class ColliderVectorDbServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IndexTool(self, request, context):
        """Index a tool for semantic search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTools(self, request, context):
        """Search for tools semantically
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColliderVectorDbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexTool': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexTool,
                    request_deserializer=collider__vectordb__pb2.ToolIndexRequest.FromString,
                    response_serializer=collider__vectordb__pb2.ToolIndexResponse.SerializeToString,
            ),
            'SearchTools': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTools,
                    request_deserializer=collider__vectordb__pb2.ToolSearchRequest.FromString,
                    response_serializer=collider__vectordb__pb2.ToolSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collider_vectordb.ColliderVectorDb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collider_vectordb.ColliderVectorDb', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColliderVectorDb(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider_vectordb.ColliderVectorDb/IndexTool',
            collider__vectordb__pb2.ToolIndexRequest.SerializeToString,
            collider__vectordb__pb2.ToolIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider_vectordb.ColliderVectorDb/SearchTools',
            collider__vectordb__pb2.ToolSearchRequest.SerializeToString,
            collider__vectordb__pb2.ToolSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
