# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collider_vectordb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'collider_vectordb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ollider_vectordb.proto\x12\x11\x63ollider_vectordb\"\x85\x01\n\x10ToolIndexRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0eorigin_node_id\x18\x03 \x01(\t\x12\x15\n\rowner_user_id\x18\x04 \x01(\t\x12\x1a\n\x12params_schema_json\x18\x05 \x01(\t\"5\n\x11ToolIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x11ToolSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x15\n\rowner_user_id\x18\x03 \x01(\t\"Z\n\tToolMatch\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x16\n\x0eorigin_node_id\x18\x04 \x01(\t\"C\n\x12ToolSearchResponse\x12-\n\x07matches\x18\x01 \x03(\x0b\x32\x1c.collider_vectordb.ToolMatch2\xc6\x01\n\x10\x43olliderVectorDb\x12V\n\tIndexTool\x12#.collider_vectordb.ToolIndexRequest\x1a$.collider_vectordb.ToolIndexResponse\x12Z\n\x0bSearchTools\x12$.collider_vectordb.ToolSearchRequest\x1a%.collider_vectordb.ToolSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collider_vectordb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLINDEXREQUEST']._serialized_start=47
  _globals['_TOOLINDEXREQUEST']._serialized_end=180
  _globals['_TOOLINDEXRESPONSE']._serialized_start=182
  _globals['_TOOLINDEXRESPONSE']._serialized_end=235
  _globals['_TOOLSEARCHREQUEST']._serialized_start=237
  _globals['_TOOLSEARCHREQUEST']._serialized_end=309
  _globals['_TOOLMATCH']._serialized_start=311
  _globals['_TOOLMATCH']._serialized_end=401
  _globals['_TOOLSEARCHRESPONSE']._serialized_start=403
  _globals['_TOOLSEARCHRESPONSE']._serialized_end=470
  _globals['_COLLIDERVECTORDB']._serialized_start=473
  _globals['_COLLIDERVECTORDB']._serialized_end=671
# @@protoc_insertion_point(module_scope)
