# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collider_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'collider_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ollider_data.proto\x12\rcollider.data\"X\n\x0e\x43ontextRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\"b\n\x11SetContextRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontainer_json\x18\x04 \x01(\x0c\"`\n\x0f\x43ontextResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontainer_json\x18\x04 \x01(\x0c\"\x96\x01\n\x10ToolRegistration\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0eorigin_node_id\x18\x02 \x01(\t\x12\x15\n\rowner_user_id\x18\x03 \x01(\t\x12\x1a\n\x12params_schema_json\x18\x04 \x01(\x0c\x12\x10\n\x08\x63ode_ref\x18\x05 \x01(\t\x12\x12\n\nvisibility\x18\x06 \x01(\t\"O\n\x18ToolRegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"J\n\rContextFilter\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08node_ids\x18\x03 \x03(\t\"o\n\x0c\x43ontextEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontainer_json\x18\x04 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x32\xda\x02\n\x0c\x43olliderData\x12K\n\nGetContext\x12\x1d.collider.data.ContextRequest\x1a\x1e.collider.data.ContextResponse\x12N\n\nSetContext\x12 .collider.data.SetContextRequest\x1a\x1e.collider.data.ContextResponse\x12X\n\x0cRegisterTool\x12\x1f.collider.data.ToolRegistration\x1a\'.collider.data.ToolRegistrationResponse\x12S\n\x14StreamContextUpdates\x12\x1c.collider.data.ContextFilter\x1a\x1b.collider.data.ContextEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collider_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTREQUEST']._serialized_start=38
  _globals['_CONTEXTREQUEST']._serialized_end=126
  _globals['_SETCONTEXTREQUEST']._serialized_start=128
  _globals['_SETCONTEXTREQUEST']._serialized_end=226
  _globals['_CONTEXTRESPONSE']._serialized_start=228
  _globals['_CONTEXTRESPONSE']._serialized_end=324
  _globals['_TOOLREGISTRATION']._serialized_start=327
  _globals['_TOOLREGISTRATION']._serialized_end=477
  _globals['_TOOLREGISTRATIONRESPONSE']._serialized_start=479
  _globals['_TOOLREGISTRATIONRESPONSE']._serialized_end=558
  _globals['_CONTEXTFILTER']._serialized_start=560
  _globals['_CONTEXTFILTER']._serialized_end=634
  _globals['_CONTEXTEVENT']._serialized_start=636
  _globals['_CONTEXTEVENT']._serialized_end=747
  _globals['_COLLIDERDATA']._serialized_start=750
  _globals['_COLLIDERDATA']._serialized_end=1096
# @@protoc_insertion_point(module_scope)
