# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import collider_data_pb2 as collider__data__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collider_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ColliderDataStub(object):
    """---------------------------------------------------------------------------
    ColliderData — gRPC service on the DataServer (:8000)

    Provides context delivery to Agent Runners and tool registration
    forwarding to the GraphToolServer.
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContext = channel.unary_unary(
                '/collider.data.ColliderData/GetContext',
                request_serializer=collider__data__pb2.ContextRequest.SerializeToString,
                response_deserializer=collider__data__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.SetContext = channel.unary_unary(
                '/collider.data.ColliderData/SetContext',
                request_serializer=collider__data__pb2.SetContextRequest.SerializeToString,
                response_deserializer=collider__data__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.RegisterTool = channel.unary_unary(
                '/collider.data.ColliderData/RegisterTool',
                request_serializer=collider__data__pb2.ToolRegistration.SerializeToString,
                response_deserializer=collider__data__pb2.ToolRegistrationResponse.FromString,
                _registered_method=True)
        self.StreamContextUpdates = channel.unary_stream(
                '/collider.data.ColliderData/StreamContextUpdates',
                request_serializer=collider__data__pb2.ContextFilter.SerializeToString,
                response_deserializer=collider__data__pb2.ContextEvent.FromString,
                _registered_method=True)


class ColliderDataServicer(object):
    """---------------------------------------------------------------------------
    ColliderData — gRPC service on the DataServer (:8000)

    Provides context delivery to Agent Runners and tool registration
    forwarding to the GraphToolServer.
    ---------------------------------------------------------------------------

    """

    def GetContext(self, request, context):
        """Read the container for a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetContext(self, request, context):
        """Write / update a container
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTool(self, request, context):
        """Register a tool defined in a container (DataServer validates,
        then forwards to GraphToolServer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamContextUpdates(self, request, context):
        """Stream real-time context updates (replaces SSE for agent runners)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColliderDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=collider__data__pb2.ContextRequest.FromString,
                    response_serializer=collider__data__pb2.ContextResponse.SerializeToString,
            ),
            'SetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.SetContext,
                    request_deserializer=collider__data__pb2.SetContextRequest.FromString,
                    response_serializer=collider__data__pb2.ContextResponse.SerializeToString,
            ),
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=collider__data__pb2.ToolRegistration.FromString,
                    response_serializer=collider__data__pb2.ToolRegistrationResponse.SerializeToString,
            ),
            'StreamContextUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamContextUpdates,
                    request_deserializer=collider__data__pb2.ContextFilter.FromString,
                    response_serializer=collider__data__pb2.ContextEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collider.data.ColliderData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collider.data.ColliderData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColliderData(object):
    """---------------------------------------------------------------------------
    ColliderData — gRPC service on the DataServer (:8000)

    Provides context delivery to Agent Runners and tool registration
    forwarding to the GraphToolServer.
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.data.ColliderData/GetContext',
            collider__data__pb2.ContextRequest.SerializeToString,
            collider__data__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.data.ColliderData/SetContext',
            collider__data__pb2.SetContextRequest.SerializeToString,
            collider__data__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collider.data.ColliderData/RegisterTool',
            collider__data__pb2.ToolRegistration.SerializeToString,
            collider__data__pb2.ToolRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamContextUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/collider.data.ColliderData/StreamContextUpdates',
            collider__data__pb2.ContextFilter.SerializeToString,
            collider__data__pb2.ContextEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
