"""Session resource management API routes (V2).

Universal Object Model v3.2.0 - Pure ResourceLink CRUD.
Legacy SessionToolInstance/SessionAgentInstance routes have been removed.
"""

from datetime import datetime, UTC

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel

from src.api.dependencies import get_user_context
from src.api.models import ErrorResponse
from src.core.agent_registry import get_agent_registry
from src.core.container import get_container
from src.core.exceptions import DepthLimitError, NotFoundError, PermissionDeniedError
from src.core.logging import get_logger
from src.core.tool_registry import get_tool_registry
from src.models.context import UserContext
from src.models.links import ResourceLink, ResourceType
from src.services.session_service import SessionService

logger = get_logger(__name__)
router = APIRouter(prefix="/sessions", tags=["Session Resources"])


# ============================================================================
# Request/Response Models
# ============================================================================


class AddResourceRequest(BaseModel):
    """Request to add a resource link to a session."""
    resource_id: str
    resource_type: ResourceType
    description: str | None = None
    role: str | None = None  # For USER type: 'owner', 'editor', 'viewer'
    preset_params: dict = {}
    input_mappings: dict = {}
    metadata: dict = {}


class UpdateResourceRequest(BaseModel):
    """Request to update a resource link."""
    description: str | None = None
    preset_params: dict | None = None
    input_mappings: dict | None = None
    metadata: dict | None = None
    enabled: bool | None = None


class ResourceListResponse(BaseModel):
    """Response for listing resources."""
    session_id: str
    resources: list[ResourceLink]
    total: int


# ============================================================================
# Dependencies
# ============================================================================


def get_session_service() -> SessionService:
    """Get session service from container."""
    container = get_container()
    return SessionService(container.firestore_client)


# ============================================================================
# V2 ResourceLink CRUD API (Universal Object Model v3.2.0)
# ============================================================================


@router.post(
    "/{session_id}/resources",
    response_model=ResourceLink,
    status_code=status.HTTP_201_CREATED,
    responses={
        400: {"model": ErrorResponse, "description": "Depth or containment violation"},
        403: {"model": ErrorResponse, "description": "Permission denied"},
        404: {"model": ErrorResponse, "description": "Resource not found or tier mismatch"},
    },
)
async def add_resource(
    session_id: str,
    request: AddResourceRequest,
    user_ctx: UserContext = Depends(get_user_context),
    session_service: SessionService = Depends(get_session_service),
):
    """
    Add a resource link to a session.
    
    Universal endpoint for all resource types: TOOL, AGENT, SOURCE, SESSION, USER.
    Validates TOOL/AGENT against registry and user tier.
    
    **Authentication Required**: Yes
    
    **Example**:
    ```json
    {
        "resource_id": "csv_analyzer",
        "resource_type": "tool",
        "description": "Q3 Sales Analysis",
        "preset_params": {"delimiter": ";"},
        "metadata": {"x": 200, "y": 150}
    }
    ```
    """
    try:
        # ACL check: Verify user has access to session
        await session_service.get(session_id, user_ctx.user_id)
        
        # Registry validation for TOOL and AGENT types
        if request.resource_type == ResourceType.TOOL:
            tool_registry = get_tool_registry()
            tool = tool_registry.get_tool(
                request.resource_id, 
                user_ctx.tier, 
                user_ctx.user_id
            )
            if not tool:
                raise HTTPException(
                    status_code=404, 
                    detail=f"Tool '{request.resource_id}' not found or not accessible for tier '{user_ctx.tier}'"
                )
        elif request.resource_type == ResourceType.AGENT:
            agent_registry = get_agent_registry()
            agent = agent_registry.get_agent(
                request.resource_id, 
                user_ctx.tier,
                user_ctx.user_id
            )
            if not agent:
                raise HTTPException(
                    status_code=404, 
                    detail=f"Agent '{request.resource_id}' not found or not accessible for tier '{user_ctx.tier}'"
                )
        # SOURCE, SESSION, USER → no registry validation needed
        
        # Create ResourceLink (link_id will be generated by service)
        link = ResourceLink(
            resource_id=request.resource_id,
            resource_type=request.resource_type,
            description=request.description,
            role=request.role,
            preset_params=request.preset_params,
            input_mappings=request.input_mappings,
            metadata=request.metadata,
            added_at=datetime.now(UTC),
            added_by=user_ctx.user_id,
            enabled=True,
        )
        
        # Service generates link_id and returns complete ResourceLink
        created_link = await session_service.add_resource_link(
            session_id,
            user_ctx.user_id,
            link,
            user_tier=user_ctx.tier,
        )
        
        logger.info(
            "Added resource",
            extra={
                "session_id": session_id,
                "link_id": created_link.link_id,
                "resource_type": request.resource_type.value,
                "resource_id": request.resource_id,
            }
        )
        
        return created_link
        
    except HTTPException:
        raise
    except DepthLimitError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except PermissionDeniedError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error("Failed to add resource", extra={"error": str(e)}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to add resource: {str(e)}")


@router.get(
    "/{session_id}/resources",
    response_model=ResourceListResponse,
    responses={
        403: {"model": ErrorResponse, "description": "Permission denied"},
        404: {"model": ErrorResponse, "description": "Session not found"},
    },
)
async def list_resources(
    session_id: str,
    type: ResourceType | None = None,
    user_ctx: UserContext = Depends(get_user_context),
    session_service: SessionService = Depends(get_session_service),
):
    """
    List resources in a session.
    
    Returns all ResourceLinks, optionally filtered by type.
    
    **Authentication Required**: Yes
    
    **Query Parameters**:
    - type: Filter by resource type (tool, agent, source, session, user)
    """
    try:
        # Get resources with optional type filter (service handles ACL)
        type_value = type.value if type else None
        resources = await session_service.get_resources(session_id, user_ctx.user_id, resource_type=type_value)
        
        return ResourceListResponse(
            session_id=session_id,
            resources=resources,
            total=len(resources),
        )
        
    except PermissionDeniedError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error("Failed to list resources", extra={"error": str(e)}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to list resources: {str(e)}")


@router.get(
    "/{session_id}/resources/{link_id}",
    response_model=ResourceLink,
    responses={
        403: {"model": ErrorResponse, "description": "Permission denied"},
        404: {"model": ErrorResponse, "description": "Resource not found"},
    },
)
async def get_resource(
    session_id: str,
    link_id: str,
    user_ctx: UserContext = Depends(get_user_context),
    session_service: SessionService = Depends(get_session_service),
):
    """
    Get a single resource by link ID.
    
    Link ID format: {type}_{resource_id}_{hex} (e.g., 'tool_csv_analyzer_a3f8b2')
    
    **Authentication Required**: Yes
    """
    try:
        resource = await session_service.get_resource_by_link_id(session_id, user_ctx.user_id, link_id)
        if not resource:
            raise HTTPException(status_code=404, detail=f"Resource '{link_id}' not found")
        return resource
        
    except HTTPException:
        raise
    except PermissionDeniedError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except Exception as e:
        logger.error("Failed to get resource", extra={"error": str(e)}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to get resource: {str(e)}")


@router.patch(
    "/{session_id}/resources/{link_id}",
    response_model=ResourceLink,
    responses={
        403: {"model": ErrorResponse, "description": "Permission denied"},
        404: {"model": ErrorResponse, "description": "Resource not found"},
    },
)
async def update_resource(
    session_id: str,
    link_id: str,
    request: UpdateResourceRequest,
    user_ctx: UserContext = Depends(get_user_context),
    session_service: SessionService = Depends(get_session_service),
):
    """
    Update a resource link.
    
    Supports partial updates to: description, preset_params, input_mappings, metadata, enabled.
    
    **Authentication Required**: Yes
    
    **Example** (move node on canvas):
    ```json
    {
        "metadata": {"x": 350, "y": 200}
    }
    ```
    """
    try:
        # ACL check
        await session_service.get(session_id, user_ctx.user_id)
        
        # Build updates dict from non-None fields
        updates = {}
        if request.description is not None:
            updates["description"] = request.description
        if request.preset_params is not None:
            updates["preset_params"] = request.preset_params
        if request.input_mappings is not None:
            updates["input_mappings"] = request.input_mappings
        if request.metadata is not None:
            updates["metadata"] = request.metadata
        if request.enabled is not None:
            updates["enabled"] = request.enabled
        
        updated_link = await session_service.update_resource_link(session_id, user_ctx.user_id, link_id, updates)
        
        logger.info(
            "Updated resource",
            extra={"session_id": session_id, "link_id": link_id, "fields": list(updates.keys())}
        )
        
        return updated_link
        
    except PermissionDeniedError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error("Failed to update resource", extra={"error": str(e)}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to update resource: {str(e)}")


@router.delete(
    "/{session_id}/resources/{link_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    responses={
        403: {"model": ErrorResponse, "description": "Permission denied"},
        404: {"model": ErrorResponse, "description": "Resource not found"},
    },
)
async def delete_resource(
    session_id: str,
    link_id: str,
    user_ctx: UserContext = Depends(get_user_context),
    session_service: SessionService = Depends(get_session_service),
):
    """
    Delete a resource link.
    
    Link ID format: {type}_{resource_id}_{hex} (e.g., 'tool_csv_analyzer_a3f8b2')
    
    **Authentication Required**: Yes
    """
    try:
        await session_service.remove_resource_link(session_id, user_ctx.user_id, link_id)
        
        logger.info(
            "Deleted resource",
            extra={"session_id": session_id, "link_id": link_id}
        )
        
        return None
        
    except HTTPException:
        raise
    except PermissionDeniedError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error("Failed to delete resource", extra={"error": str(e)}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to delete resource: {str(e)}")
